# Limpiar pantalla
import time 
import os
def limpiar():
    if os.name == "nt":
        os.system("cls")
    else:
        os.system("clear")

# def decorarHeader(multi01,multi02):
#   print("+"*1 + "-"*multi01 + "+"*1 + "-"*multi02 + "+"*1)

# def crearTablaTextCenter(text01,multi01):
#     print("│",text01.center(multi01, " "),"{:<0}".format("│") )

# def crearTabla2TextCenter(text01,text02,multi01,multi02):
#     print("│",text01.center(multi01, " ") ,"│",text02.center(multi02, " "), "{:>0}".format("│") )

# def crearTabla2Text(text01,text02,multi01,multi02):
#     print(text01,(" "*multi01),"{:<0}".format("")  ,text02,(" "*multi02), "{:>0}".format("│") )

#nuevo menu
def nuevaLineaSuperior(var01):
  print("▄"*var01)

def nuevaLineaInferior(var01):
  print("▀"*var01)

def nuevaLineaSinContenido(var01):
  print("█"*var01)

def nuevoTextoCentrado(var01,var02):
    print(" ",var01.center(var02, " "),"{:<0}".format(" ") )

def nuevaLineasinContenidoInteriorVacio(multi01):
  print("███"*1 + " "*multi01 + "███"*1)

def contInterior(text01,multi01):
    print("███",text01.center(multi01, " "),"{:<0}".format("███") )

def contExterior(text01,multi01):
    print(" ",text01.center(multi01, " "),"{:<0}".format(" ") )

# limpieza de pantalla mas mensaje que vuelve al menu
def volviendoAlMenuPipati():
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     .                                          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ..                                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ...                                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... V                                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Vo                                     ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volv                                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvi                                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvie                                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvien                                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo                              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo a                            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al                           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al M                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al ME                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MEN                       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ P                    ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PI                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PIP                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PIPA                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PIPAT                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PIPATI               ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(1.5)
  limpiar()

def volviendoAlMenuPrincipal():
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     .                                          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ..                                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ...                                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... V                                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Vo                                     ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volv                                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvi                                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvie                                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvien                                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo                              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo a                            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al                           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al M                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al ME                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MEN                       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ P                    ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PR                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRI                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRIN                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRINC                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRINCI               ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
 
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRINCIP              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRINCIPA             ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ PRINCIPAL            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(1.5)
  limpiar()

def volviendoAlMenuDados():
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     .                                          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ..                                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ...                                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... V                                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Vo                                     ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volv                                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvi                                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvie                                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvien                                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo                              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo a                            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al                           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al M                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al ME                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MEN                       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ D                    ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DA                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DAD                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DADO                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DADOS                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(1.5)
  limpiar()

def volviendoAlMenuAhorcado():
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     .                                          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ..                                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ...                                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... V                                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Vo                                     ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volv                                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvi                                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvie                                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvien                                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo                              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo a                            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al                           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al M                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al ME                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MEN                       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ A                    ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AH                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHO                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHOR                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHORC                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHORCA               ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
 
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHORCAD              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ AHORCADO             ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(1.5)
  limpiar()

def volviendoAlMenuEstadisticas():
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     .                                          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ..                                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ...                                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... V                                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Vo                                     ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volv                                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvi                                  ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvie                                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volvien                                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo                              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo a                            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al                           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al M                         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al ME                        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MEN                       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ                      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ D                    ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE                   ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE E                 ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ES                ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE EST               ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTA              ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
 
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTAD             ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍ            ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍS           ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍST          ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍSTI         ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍSTIC        ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)
  time.sleep(0.1)
  
  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍSTICA       ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)  
  time.sleep(0.1)

  limpiar()
  nuevaLineaSuperior(146)
  contInterior("                                                ",138)
  contInterior("     ... Volviendo al MENÚ DE ESTADÍSTICAS      ",138)
  contInterior("                                                ",138)
  nuevaLineaInferior(146)  
  time.sleep(1.5)
  limpiar()
